### ISSUE TITLE
Unbound does not create dnstap socket

### ISSUE THREAD

**Issue by jpds** [NLnetLabs/unbound#952] opened 2023-10-15 16:16 UTC
**Describe the bug**

Unbound appears to try to connect to it's own dnstap socket before it is created:

```
Oct 15 15:49:16 dns1 unbound-pre-start[1464703]: setup in directory /var/lib/unbound
Oct 15 15:49:17 dns1 unbound-pre-start[1464703]: removing artifacts
Oct 15 15:49:17 dns1 unbound-pre-start[1464703]: Setup success. Certificates created. Enable in unbound.conf file to use
Oct 15 15:49:18 dns1 unbound[1464714]: [1464714:0] notice: init module 0: validator
Oct 15 15:49:18 dns1 unbound[1464714]: [1464714:0] notice: init module 1: iterator
Oct 15 15:49:18 dns1 unbound[1464714]: [1464714:0] notice: attempting to connect to dnstap socket /run/unbound/dnstap.socket
Oct 15 15:49:18 dns1 unbound[1464714]: [1464714:0] warning: could not open dnstap-socket-path: /run/unbound/dnstap.socket, No such file or directory
Oct 15 15:49:18 dns1 unbound[1464714]: [1464714:0] notice: dnstap identity field set to "dns1"
Oct 15 15:49:18 dns1 unbound[1464714]: [1464714:0] notice: dnstap version field set to "unbound 1.18.0"
Oct 15 15:49:18 dns1 unbound[1464714]: [1464714:0] notice: dnstap Message/RESOLVER_RESPONSE enabled
Oct 15 15:49:18 dns1 unbound[1464714]: [1464714:0] notice: dnstap Message/CLIENT_QUERY enabled
Oct 15 15:49:18 dns1 unbound[1464714]: [1464714:5] error: dnstap io: failed to connect to "/run/unbound/dnstap.socket": No such file or directory
Oct 15 15:49:18 dns1 unbound[1464714]: [1464714:5] error: dnstap io: failed to connect to "/run/unbound/dnstap.socket": No such file or directory
Oct 15 15:49:18 dns1 systemd[1]: Started Unbound recursive Domain Name Server.
```

It is configured as follows:

```
dnstap:
  dnstap-enable: yes
  dnstap-log-client-query-messages: yes
  dnstap-log-resolver-response-messages: yes
  dnstap-send-identity: yes
  dnstap-send-version: yes
  dnstap-socket-path: /run/unbound/dnstap.socket
```

It has no issues creating it's control socket:

```
$ ls -l /run/unbound/
srw-rw---- 1 unbound unbound 0 Oct 15 15:52 unbound.socket
```

And the systemd unit grants it access to create Unix sockets:

```
RestrictAddressFamilies=AF_UNIX
```

Tested on both 1.17.1 and 1.18.0 on NixOS. I'm hoping to feed this socket straight into https://vector.dev/docs/reference/configuration/sources/dnstap/

**Comment by edmonds** [comment] 2023-10-23 19:47
This is not a bug, this is how dnstap is designed. Unbound is a client that connects to a dnstap socket and writes data to that socket. You need a separate server running to provide the dnstap socket for Unbound to connect to.

From the Unbound documentation:

> dnstap-socket-path: \<file name\>
> Sets the unix socket file name for **_connecting_** to the server that is listening on that socket.  Default is "/run/dnstap.sock".

From the Vector documentation that you linked (https://vector.dev/docs/reference/configuration/sources/dnstap/#server-unix-domain-socket-uds):

> The [Vector agent's] dnstap source receives dnstap data through a Unix Domain Socket (aka UDS). The path of the UDS must be explicitly specified in the source’s configuration.
>
> Upon startup, the [Vector agent's] dnstap source **_creates_** a new server UDS at the specified path. If the path of UDS is already in use, Vector automatically deletes it before creating a new path.

So you need to configure Vector (dnstap server) and Unbound (dnstap client) to use the same dnstap unix socket path and to start the Vector server at some point (Unbound will automatically attempt to periodically reconnect to the socket if it is not available).

This is identical to how Unix daemons are syslog clients and a separate syslog server is needed to receive log messages and write them to disk, and the daemons will be unable to log to syslog if the syslog daemon is not running.

**Comment by gthess** [comment] 2023-10-30 10:51
Indeed, Unbound only tries to connect to the socket-path location; closing this as non-issue.

**Closed as completed by gthess** 2023-10-30 10:51 UTC
