### ISSUE TITLE
Recursive mode NODATA after network failure 

### ISSUE THREAD

**Issue by ja-pa** [NLnetLabs/unbound#465] opened 2021-04-16 14:15 UTC
Hi,
we noticed weird behavior with unbound 1.13.0 (running on the router) in recursive mode and unbound 1.9.0-2+deb10u2  running on a different network.

There was network failure and after the connection was restored unbound refused to do any recursion for queries that were asked during network failure and just immediately returned NODATA. Queries that were not asked during network failure were resolved (via recursion) correctly.
Testing showed during the next network failures that unbound started doing recursion for "cached" queries again either after 1-2 hours or after restarting unbound daemon.

Setting cache-max-negative-ttl to some small number (like 15s) helped and unbound started doing recursion without the need to wait 1-2 hours or need to manually restart it.

Workaround with cache-max-negative-ttl is still working, but we have no idea what could go wrong and why it is helping.

Unbound config:
```
$ cat /var/etc/unbound/unbound.conf
# auto-generated config file from /etc/config/resolver
server:
        chroot: ""
        verbosity: 0
        interface: 0.0.0.0
        interface: ::0
        port: 53
        auto-trust-anchor-file: /etc/root.keys
        edns-buffer-size: 4096
        msg-cache-size: 20M
        do-ip4: yes
        do-ip6: yes
        prefetch: yes
  local-zone: "lan." static
        outgoing-range: 60
        outgoing-num-tcp: 1
        incoming-num-tcp: 1
        msg-cache-slabs: 1
        num-queries-per-thread: 30
        rrset-cache-slabs: 1
        rrset-cache-size: 100K
        infra-cache-slabs: 1
        infra-cache-numhosts: 200
        access-control: 0.0.0.0/0 allow
        access-control: ::0/0 allow
        username: ""
        pidfile: "/var/run/unbound.pid"
        root-hints: "/etc/unbound/named.cache"
        target-fetch-policy: "2 1 0 0 0"
        harden-short-bufsize: yes
        harden-large-queries: yes
        qname-minimisation: yes
        harden-below-nxdomain: yes
        key-cache-size: 100k
        key-cache-slabs: 1
        neg-cache-size: 10k
        prefetch: yes
        prefetch-key: yes
include: "/etc/unbound/cache-max-negative-ttl.conf"
include: "/etc/unbound/disable-upstream-ipv6.conf"
python:
remote-control:
        control-enable: yes
        control-interface: 127.0.0.1
        control-use-cert: no
        control-port: 8953
        server-key-file: "/etc/unbound/unbound_server.key"
        server-cert-file: "/etc/unbound/unbound_server.pem"
        control-key-file: "/etc/unbound/unbound_control.key"
        control-cert-file: "/etc/unbound/unbound_control.pem"
$ cat /etc/unbound/cache-max-negative-ttl.conf
server:
        cache-max-negative-ttl: 15
$ cat /etc/unbound/disable-upstream-ipv6.conf
server:
        outgoing-interface: 0.0.0.0
```
cc @pali

**Comment by gthess** [comment] 2021-04-16 14:47
It's not clear to me what the network connection is between the two unbound instances, unless you mean that you see the behavior on two different instances on two different networks.

I would expect to see SERVFAIL during the network failure; unbound can't contact upstreams and there is nothing to return to the client. Unbound would not forge NODATA responses. Failures to connect to upstreams would be recorded so when the network is working again, unbound would *slowly* start sending traffic to upstreams again.

It seems that during the network failure, unbound somehow gets NODATA answers and caches them (in the negative cache) for a maximum of 3600 seconds (default). These cached answers are served until they expire, which in your case is even after the network is working again.

It would help you to see what happens with unbound during the network failure. High verbosity (3) and looking at the log should be enough.

**Comment by pali** [comment] 2021-04-16 15:18
Hello @gthess! Network failure was somewhere on ISP network, meaning that box with unbound had ethernet link, had assigned IPv4 address but internet connection was not working. I do not have high verbosity logs from time when it happens and because network failure was not on my side, I cannot say what happened nor I cannot reproduce it.

I observed same issue on two different networks. Machines on these networks do not share anything, they are just independent instances. Meaning: I hit this issue with two different unbound versions which are running on two different networks. So this issue is not specific to one platform / network / version.

I really do not know what is happening here. I just figured out that setting cache-max-negative-ttl to 15 helped and next similar network failure did not cause that unbound to not respond for queries. As `dig` saw NODATA when this issue happened I tried to find some unbound option related to NODATA and caching; which was cache-max-negative-ttl.

Enabling permanent high verbosity is not possible on these boxes as they have limited storage and unbound generates too much lines. Moreover as it happens only when ISP has unexpected network failures, it is hard to simulate it or to "wait for this failure". Also as having internet connection is required on these boxes, I really should not remove current workaround via cache-max-negative-ttl as another unexpected network failure cause again 1-2 hours DNS issues.

I'm not sure if this helps you to understand this issue. But if you have anything else which could help you, please let me know.

**Comment by gthess** [comment] 2021-04-16 15:31
Hi @pali!
Since I don't have any extra information and I understand it is difficult to get logging output I am going to *guess* that when your ISP knows it is down it maybe answers your queries with NODATA responses? Which *may* mean that they filter plain DNS and when there is no upstream connectivity, for them to get an answer to filter, they just return a NODATA response.

Again this is *highly speculative* and the only thing that comes to mind now.

You can check with DNSSEC signed domains during the network failure; I expect those to properly return SERVFAIL.

`cache-max-negative-ttl` helps because it limits the time these NODATA answers are kept in the cache.

**Comment by pali** [comment] 2021-04-16 15:49
> `cache-max-negative-ttl` helps because it limits the time these NODATA answers are kept in the cache.

Obviously, in above scenario it makes sense that it helps.

I was not thinking about such fact that ISP can hijack DNS traffic during network failure. But I know that some ISP modify/filter DNS packets, so it is not impossible.

But, one network is connected via external DOCSIS modem and during this network failure I remember that modem blinked in a way that indicated that it was not connected to CMTS (ISP device on the other side of the link). So in case this speculative scenario happened on DOCSIS network, those "fake" DNS packets must have been generated by modem itself. But because this is dumb modem (one coax port, one eth port, no switch, no wifi, just dumb bridge between ethernet and coax) which have no configuration, I highly doubt that it support such kind deep packet inspection and generate fake DNS packets...

But if this is really truth, I could use just simple dig command during network failure to random non-DNS IPv4 address and see if I receive any reply or just timeout. I could also try to disconnect coax cable from modem and see if it starts answering to DNS packets.

I guess that for DNSSEC protected domains, there must be some failure, not NODATA. That is a good idea for testing.

**Comment by gthess** [comment] 2023-03-17 14:59
Closing this as a non issue; it seems to be related with the specific network environment. Feel free to reopen/ping :)

**Closed as completed by gthess** 2023-03-17 14:59 UTC
