### ISSUE TITLE
sendmsg() with ancillary data fails with EINVAL

### ISSUE THREAD

**Issue by drboone** [NLnetLabs/unbound#945] opened 2023-09-29 20:34 UTC
Between 1.17.1 and 1.18.0, this patch was applied in util/netevent.c - comm_point_create_udp():
```
@@ -3809,7 +3860,11 @@
    evbits = UB_EV_READ | UB_EV_PERSIST;
    /* ub_event stuff */
    c->ev->ev = ub_event_new(base->eb->base, c->fd, evbits,
+#ifdef USE_WINSOCK
        comm_point_udp_callback, c);
+#else
+       comm_point_udp_ancil_callback, c);
+#endif
    if(c->ev->ev == NULL) {
        log_err("could not baseset udp event");
        comm_point_delete(c);
```
This results in use of sendmsg() for responses where send() or sendto() used to be called in at least some cases.  Given that there is a separate comm_point_create_udp_ancil(), the patch seems erroneous anyway, but the additional problem is that unbound then ends up using the incorrect sendmsg() semantics on SmartOS, I think due to an old decision about libsocket vs libxnet.  Calling old-semantics sendmsg() with ancillary data results in EINVAL.  This issue probably obtains on many Solaris derived platforms.

The affected systems are running unbound binaries installed with pkgsrc tooling.  Identical results obtain if I use the pkgsrc tooling to build from source.

**To reproduce**
1. Install unbound 1.18.0 from pkgsrc
2. Send A queries from a host on the local lan for which the answer should be short
3. Get no response, see unbound syslog something akin to `unbound|[161595:1d] notice: sendmsg failed: Invalid argument`

**Expected behavior**
Get a response in step 3.

**System:**
 - Unbound version: 1.18.0
 - OS: SmartOS 20230504T000449Z
 - `unbound -V` output:
```
Version 1.18.0

Configure line: --enable-allsymbols --with-libexpat=/opt/local --with-libevent=/opt/local --enable-event-api --with-ssl=/opt/local --with-pidfile=/var/run/unbound/unbound.pid --sysconfdir=/opt/local/etc --with-libnghttp2=/opt/local --enable-gost --enable-sha2 --with-libiconv-prefix=/opt/local --prefix=/opt/local --build=x86_64-sun-solaris2.11 --host=x86_64-sun-solaris2.11 --mandir=/opt/local/man --enable-option-checking=yes
Linked libs: pluggable-libevent 2.1.12-stable (it uses evport), OpenSSL 1.1.1w  11 Sep 2023
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Comment by jperkin** [comment] 2023-10-03 12:09
I took a look at this to see exactly why it's returning `EINVAL`.  The setup is a build of unbound 1.18.0 from pkgsrc, running on localhost, then using `dig(1)` with a short query.

Notably, the first run always succeeds, but subsequent ones fail.

```
$ dig +short www.bbc.co.uk @127.0.0.1
www.bbc.co.uk.pri.bbc.co.uk.
bbc.map.fastly.net.
146.75.80.81
$ dig +short www.bbc.co.uk @127.0.0.1
;; connection timed out; no servers could be reached
```

The failed second run corresponds with unbound printing the `sendmsg failed` errors to stdout (at least when running `unbound -dv` as I am).

First, run a speculative DTrace on `sendmsg()` to trace when `errno` is set using the following script:

```
#!/usr/sbin/dtrace -Fs

syscall::*sendmsg:entry
{
        self->spec = speculation();
        speculate(self->spec);
}

fbt:::
/self->spec/
{
        speculate(self->spec);
}

syscall::*sendmsg:return
/self->spec/
{
        speculate(self->spec);
        trace(errno);
}

syscall::*sendmsg:return
/self->spec && errno != 0/
{
        commit(self->spec);
        self->spec = 0;
}

syscall::*sendmsg:return
/self->spec && errno == 0/
{
        discard(self->spec);
        self->spec = 0;
}
```

The output of this running against the unbound PID is:

```
CPU FUNCTION                                   
 15  -> sendmsg                               
 15    -> get_udatamodel                       
 15    <- get_udatamodel                       
 15    -> copyin                               
 15    <- kcopy                                
 15    -> copyin                               
 15    <- kcopy                                         
 15    -> sendit                               
 15      -> getsonode                          
 15        -> getf                             
 15          -> getf_gen                       
 15            -> set_active_fd                
 15            <- set_active_fd                
 15            -> set_active_fd                
 15            <- set_active_fd                
 15          <- getf_gen                       
 15        <- getf                             
 15      <- getsonode                          
 15      -> copyin_name                        
 15        -> kmem_alloc                       
 15          -> kmem_cache_alloc               
 15          <- kmem_cache_alloc               
 15        <- kmem_alloc                               
 15        -> copyin                           
 15        <- kcopy                            
 15      <- copyin_name                       
 15      -> kmem_alloc                         
 15        -> kmem_cache_alloc                 
 15        <- kmem_cache_alloc                 
 15      <- kmem_alloc                         
 15      -> copyin                             
 15      <- kcopy                                       
 15      -> socket_sendmsg                     
 15        -> so_sendmsg                       
 15          -> socopyinuio                    
 15            -> allocb                       
 15              -> kmem_cache_alloc           
 15              <- kmem_cache_alloc           
 15            <- allocb                       
 15            -> uiomove                      
 15              -> xcopyin_nta                
 15              <- kcopy                      
 15            <- uiomove                      
 15          <- socopyinuio                    
 15          -> udp_send                       
 15            -> proto_verify_ip_addr        
 15            <- proto_verify_ip_addr        
 15            -> udp_output_ancillary        
 15              -> conn_get_ixa_exclusive    
 15                -> kmem_alloc               
 15                  -> kmem_cache_alloc      
 15                  <- kmem_cache_alloc      
 15                <- kmem_alloc               
 15                -> ixa_safe_copy            
 15                <- ixa_safe_copy            
 15              <- conn_get_ixa_exclusive    
 15              -> ip_attr_newdst             
 15              <- ip_attr_newdst             
 15              -> kmem_zalloc                
 15                -> kmem_cache_alloc        
 15                <- kmem_cache_alloc        
 15              <- kmem_zalloc                
 15              -> ip_pkt_copy                
 15              <- ip_pkt_copy                
 15              -> process_auxiliary_options 
 15                -> proto_opt_lookup        
 15                <- proto_opt_lookup        
 15                -> udp_opt_set              
 15                  -> udp_opt_allow_udr_set 
 15                  <- udp_opt_allow_udr_set 
 15                  -> udp_do_opt_set        
 15                    -> conn_opt_set        
 15                      -> conn_opt_set_ipv6 
 15                      <- conn_opt_set_ipv6 
 15                    <- conn_opt_set        
 15                  <- udp_do_opt_set        
 15                <- udp_opt_set              
 15              <- process_auxiliary_options 
 15              -> freemsg                    
 15                -> dblk_lastfree            
 15                  -> kmem_cache_free       
 15                  <- kmem_cache_free       
 15                <- dblk_lastfree            
 15              <- freemsg                    
 15              -> ixa_refrele                                                                                                                       
 15                -> ixa_inactive                                                                                                                    
 15                  -> ixa_cleanup            
 15                  <- ixa_cleanup            
 15                  -> kmem_free              
 15                    -> kmem_cache_free     
 15                    <- kmem_cache_free     
 15                  <- kmem_free              
 15                <- ixa_inactive             
 15              <- ixa_refrele                
 15              -> ip_pkt_free                
 15              <- ip_pkt_free                
 15              -> kmem_free                  
 15                -> kmem_cache_free          
 15                <- kmem_cache_free          
 15              <- kmem_free                  
 15            <- udp_output_ancillary        
 15          <- udp_send                       
 15        <- so_sendmsg                       
 15      <- socket_sendmsg                     
 15      -> kmem_free                          
 15        -> kmem_cache_free                  
 15        <- kmem_cache_free                  
 15      <- kmem_free                          
 15      -> kmem_free                          
 15        -> kmem_cache_free                  
 15        <- kmem_cache_free                  
 15      <- kmem_free                          
 15      -> releasef                           
 15        -> clear_active_fd                  
 15        <- clear_active_fd                  
 15        -> cv_broadcast                     
 15        <- cv_broadcast                     
 15      <- releasef                           
 15      -> set_errno                          
 15      <- set_errno                          
 15    <- sendit                               
 15  <- sendmsg                                
 15  <= sendmsg                                      22
```

That's odd.  I am specifically using IPv4, but `conn_opt_set_ipv6()` is being called, and being the deepest entry in the callstack is likely where errno is being set.

Looking at https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/inet/ip/conn_opt.c#L1543-L1544 we can see:

```
	if (connp->conn_family != AF_INET6)
		return (EINVAL);
```

and we can confirm that this is where `EINVAL` is being returned by again using DTrace to see what the input `conn_family` is:

```
$ dtrace -p "$(pgrep unbound)" -n 'conn_opt_set_ipv6:entry/pid==$target/ {print(((conn_t *)(args[0])->coa_connp)->conn_family);}'
dtrace: description 'conn_opt_set_ipv6:entry' matched 1 probe
CPU     ID                    FUNCTION:NAME
 10  40388          conn_opt_set_ipv6:entry sa_family_t 0x2
```

```
$ grep AF_INET /usr/include/sys/socket.h
#define AF_INET         2               /* internetwork: UDP, TCP, etc. */
#define AF_INET6        26              /* Internet Protocol, Version 6 */
```

So this appears to be the cause of the bug, trying to set IPv6 options on an IPv4 socket.

Let's use DTrace to find the code in unbound that calls the failing `sendmsg()` (`arg1` is the return value, so print a user stack when it returns `!= 0`):

```
$ dtrace -p "$(pgrep unbound)" -n 'sendmsg:return/pid == $target && arg1/ { ustack(); }'
 10    785                   sendmsg:return 
              libc.so.1`__so_sendmsg+0xa
              libsocket.so.1`__xnet_sendmsg+0x15
              libunbound.so.8.1.22`comm_point_send_udp_msg_if.isra.0+0x293
              libunbound.so.8.1.22`comm_point_udp_ancil_callback+0x2fc
              libevent-2.1.so.7.0.1`event_process_active_single_queue+0x5ba
              libevent-2.1.so.7.0.1`event_base_loop+0x4bf
              libunbound.so.8.1.22`comm_base_dispatch+0x19
              unbound`daemon_fork+0x544
              unbound`main+0x4c0
              unbound`_start_crt+0x87
              unbound`_start+0x18
```

Looking at the unbound code for `comm_point_send_udp_msg_if()` the logic appears to be:

```
        if(r->srctype == 4) {
                cmsg->cmsg_level = IPPROTO_IP;
        } else if(r->srctype == 6) {
                cmsg->cmsg_level = IPPROTO_IPV6;
        } else {
                cmsg->cmsg_level = IPPROTO_IPV6;
```

Adding some manual debug code here shows that `srctype == 0`, and thus `IPPROTO_IPV6` is being used. This appears to be the default value set in `comm_point_udp_ancil_callback()`, and it's not clear to me at first glance why neither of the IPv4 or IPv6 branches are being taken. Hopefully you folks will know what to do pretty quickly based on this information.

Out of interest, yes: if I explicitly specify the IPv6 loopback address then it always works fine:

```
$ dig +short www.bbc.co.uk @::1
www.bbc.co.uk.pri.bbc.co.uk.
bbc.map.fastly.net.
146.75.76.81
$ dig +short www.bbc.co.uk @::1
www.bbc.co.uk.pri.bbc.co.uk.
bbc.map.fastly.net.
146.75.76.81
[...]
```

Hope this helps.

**Comment by gthess** [comment] 2023-10-31 14:55
Thanks for all the data! I believe this is already solved with 1c8f0e0fc5056e95fed87206ef6f81aed4d209d1.
Could you verify?

**Comment by gaige** [comment] 2023-11-12 16:03
Looks like the patch works on SmartOS using 1.19.0.

**Comment by gthess** [comment] 2023-11-13 08:33
Thanks! Closing this then.

**Closed as completed by gthess** 2023-11-13 08:33 UTC
