### ISSUE TITLE
RPZ Logging irregularity

### ISSUE THREAD

**Issue by deteque** [NLnetLabs/unbound#635] opened 2022-02-27 20:58 UTC
This isn't a big issue, but RPZ logging for hosts and domains produces this label in the log file:
i**nfo: rpz: applied**

However, it appears that rpz-ip triggers result in this label:
**info: RPZ applied** 

The "rpz" is capitalized and doesn't have a trailing colon after it.

While mostly cosmetic, it would make regexes simpler if the RPZ logging was more consistent.

**Comment by gthess** [comment] 2022-02-28 11:09
Closing as a duplicate of #630 (which is now fixed).
"rpz:" was chosen.

**Closed as completed by gthess** 2022-02-28 11:09 UTC
