### ISSUE TITLE
Unbound does not recover after network outage

### ISSUE THREAD

**Issue by minfrin** [NLnetLabs/unbound#830] opened 2023-01-16 09:05 UTC
**Describe the bug**
After an upstream extended outage resolved some 12 hours prior, unbound continued returning "connection timed out" until restarted.

**To reproduce**
1. Unbound configured as a standalone resolver
2. 48 hour upstream outage where internet was 99% gone (but not 100%)
3. Wait 12 hours after internet recovery, attempt to resolve google.com, get connection timed out.

**Expected behavior**
Successful resolution

**System:**
 - Unbound version: unbound-1.7.3
 - OS: Rocky 8
 - `unbound -V` output: unbound: invalid option -- 'V'

**Additional information**

Restarting unbound resolved the immediate outage, looks like unbound does not recover from upstream failures.

```
beachfront ~ # cat /etc/resolv.conf 
nameserver ::1
options edns0
beachfront ~ # dig google.com

; <<>> DiG 9.11.36-RedHat-9.11.36-3.el8 <<>> google.com
;; global options: +cmd
;; connection timed out; no servers could be reached
beachfront ~ # date
Mon Jan 16 10:10:22 SAST 2023
beachfront ~ # ps -aux | grep unbound
root     4150771  0.0  0.0      0     0 ?        I    09:49   0:00 [kworker/u16:1-events_unbound]
root     4151085  0.0  0.0      0     0 ?        I    09:54   0:00 [kworker/u16:2-events_unbound]
root     4151671  0.0  0.0      0     0 ?        I    10:01   0:00 [kworker/u16:0-events_unbound]
root     4151968  0.0  0.0      0     0 ?        I    10:05   0:00 [kworker/u16:3-events_unbound]
root     4152441  0.0  0.0 221936  1100 pts/0    S+   10:10   0:00 /bin/grep --color=auto unbound
(reverse-i-search)`unbound': ps -aux | grep ^Cbound
beachfront ~ # systemctl restart unbound
beachfront ~ # dig google.com

; <<>> DiG 9.11.36-RedHat-9.11.36-3.el8 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42633
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		300	IN	A	172.217.170.46

;; Query time: 536 msec
;; SERVER: ::1#53(::1)
;; WHEN: Mon Jan 16 10:11:26 SAST 2023
;; MSG SIZE  rcvd: 55

```

**Comment by gthess** [comment] 2023-01-16 10:06
Hi there,

Unbound records nameserver specific information in the infrastructure cache; this includes the nameserver responsiveness. So during the outage Unbound incrementally raises the time it is willing to wait for a response from a server until it marks that nameserver as being down.

Usually issuing `unbound-control flush_infra all` should immediately work.

Additionally, using [infra-keep-probing: yes](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-infra-keep-probing) in the configuration will keep probing nameservers that were marked as down.

However what I see in your case is that dig does not get an answer and that the issue is resolved for 12 hours already.
In case of all the servers being marked as down, Unbound would return SERVFAIL.
The timeout suggests that Unbound was busy trying to do something. Do you have any logging information available?

If you can reproduce the behavior, could you increase the verbosity with `unbound-control verbosity 4` and gather some logging along with trying my proposed solution above?

**Comment by gthess** [comment] 2023-10-02 14:59
Closing as inactive non-issue. Feel free to ping here with further information if/when available.

**Closed as completed by gthess** 2023-10-02 14:59 UTC
