### ISSUE TITLE
Segfault with glibc 2.33

### ISSUE THREAD

**Issue by dvzrv** [NLnetLabs/unbound#418] opened 2021-02-04 10:15 UTC
Hi! I'm packaging unbound for Arch Linux. We have recently upgraded glibc to 2.33 in our testing repository and are now looking into an issue with unbound, which manifests as a segfault on start: https://bugs.archlinux.org/task/69532

I will try to provide more info later, if the original author of that ticket does not do that before me.

**Comment by wcawijngaards** [comment] 2021-02-04 10:55
So it fails in `initgroups` which is a system call at startup that unbound uses to drop user privileges.  Unbound calls it with the username and the group id.  The stack trace shows grouplist, is there something wrong with the users's setup for the unbound user name?  Or what user is configured to be used by the config file. With the option `username` in unbound.conf, it can also be set with ./configure --with-username and defaults to 'unbound'.

That said, the code does not check the gid value passed to initgroups, and could pass -1 for the groupid.   When I do this the result is an error for `Invalid argument` and it does not crash for that.  So I do not see how it could crash there, what with unbound passing a nonNULL username.  It just checks that on the line above that the username argument is not NULL.

**Comment by diabonas** [comment] 2021-02-04 11:17
The issue is that `initgroups()` in glibc 2.33 crashes if the function is called within a chroot. There is already an [upstream glibc bug report for this](https://sourceware.org/bugzilla/show_bug.cgi?id=27343), so hopefully the issue should get fixed without any necessary changes in Unbound.

As a workaround for systems with glibc 2.33, you can disable the chrooting in Unbound by setting `chroot: ""` in `unbound.conf`.

FWIW, I haven't been able to create a minimal chroot that makes glibc happy yet (e.g. by adding `/etc/unbound/etc/nsswitch.conf`, `/etc/unbound/etc/group`, ... if `/etc/unbound` is the chroot directory).

**Comment by trofi** [comment] 2021-02-05 06:57
`initgroups()` should probably be called before a `chroot()`. It's unfortunate that glibc crashes in this scenario, but it will probably not work as expected anyway.

**Comment by wcawijngaards** [comment] 2021-02-05 07:38
But if you drop user privileges, the chroot call may not be possible any more, because that needs root privilege.

**Comment by trofi** [comment] 2021-02-05 08:36
Ah, good point! I somehow thought `initgroups()` does not call `setgoups()` internally (and only preloads the values into memory), but it does.

**Comment by trofi** [comment] 2021-02-05 08:44
How about something like:

Before:
```c
chroot();
initgroups();
```

After:
```c
getgroups(); // uses libc, NSS facility
chroot();
setgroups(); // only calls kernel directly
```

**Comment by wcawijngaards** [comment] 2021-02-05 12:34
I would prefer to not mess with group ids in unbound, if this is fixed in the glibc bug report (at some point).  The aim is to drop privileges as much as possible, and messing with the group lists sounds counterproductive for security.

Additionally, getgroups gets the groups for the current user. So the setgroups call would then not actually drop group privileges, I guess.

**Comment by trofi** [comment] 2021-02-05 14:29
Waiting on glibc fix makes sense.

I did not realize `getgroups()` is so limited, my apologies. For completeness I'll amend my suggestion slightly with `s/getgroups()/getgrouplist()/`. That's what glibc implementation does https://sourceware.org/git/?p=glibc.git;a=blob;f=grp/initgroups.c;h=6164d16fc03affec29b3e76760e73689b21af435;hb=HEAD#l174 and FreeBSD manpages suggest to happen: https://www.freebsd.org/cgi/man.cgi?query=initgroups&apropos=0&sektion=3#end.

```c
getgrouplist(); // uses libc, NSS facility
chroot();
setgroups(); // only calls kernel directly
```

**Comment by ArchangeGabriel** [comment] 2021-07-24 14:43
This has been fixed upstream and backported in Arch (https://github.com/archlinux/svntogit-packages/commit/88b2820a8b13b42531de683cffda921d46b8671b), should be closed now I think.

**Comment by wcawijngaards** [comment] 2021-07-26 09:35
The group permission drop needs to have correct security, the old code has it, so it stays, now that it is fixed elsewhere. Thanks for the suggestion for fixed code, that is very helpful.

**Closed as completed by wcawijngaards** 2021-07-26 09:35 UTC
