### ISSUE TITLE
unbound-checkconf rejects correct ubnound.conf

### ISSUE THREAD

**Issue by ip75** [NLnetLabs/unbound#613] opened 2022-01-25 22:30 UTC
**Describe the bug**
Unbound is not start when I use interface name instead of IP address in config file.

```
unbound.conf
....
   interface: em1
....
```

let's try to restart service

```
[root:~]# service unbound restart
Obtaining a trust anchor...
[1643149748] unbound-checkconf[18933:0] fatal error: cannot parse interface specified as 'em1'
/usr/local/etc/rc.d/unbound: WARNING: failed precmd routine for unbound
```

```
[root:~]# man unbound.conf

...
       interface: <ip address[@port]>
              Interface to use to connect to the network. This interface is
              listened to for queries from clients, and answers to clients are
              given from it.  Can be given multiple times to work on several
              interfaces. If none are given the default is to listen to
              localhost.  *If an interface name is used instead of an ip
              address, the list of ip addresses on that interface are used.*   <--------------------------------
              The interfaces are not changed on a reload (kill -HUP) but only
              on restart.  A port number can be specified with @port (without
              spaces between interface and port number), if not specified the
              default port (from port) is used.
...
```

network interface em1

```
[root:~]# ifconfig em1
em1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=81209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,VLAN_HWFILTER>
        ether 90:e2:ba:80:fc:a7
        inet 10.108.1.1 netmask 0xffffff00 broadcast 10.108.1.255
        inet 10.108.1.12 netmask 0xffffffff broadcast 10.108.1.12
        media: Ethernet 1000baseT (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```

**To reproduce**
1. use name of interface instead of ip address in `unbound.conf` as mentioned in manual
2. restart unbound service

**Expected behavior**

**System:**
 - Unbound version:
 - OS:
```
[root:~]# uname -a
FreeBSD bvgm.org 12.2-RELEASE-p10 FreeBSD 12.2-RELEASE-p10 12803d8a99c(releng/12.2) BVGM  amd64
```

 - `unbound -V` output:
```
[root:~]# unbound -V
Version 1.13.1

Configure line: --with-ssl=/usr --with-libexpat=/usr/local --disable-dnscrypt --disable-dnstap --with-libnghttp2 --enable-ecdsa --disable-event-api --enable-gost --with-libevent --disable-subnet --disable-tfo-client --disable-tfo-server --with-pthreads --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/share/info/ --build=amd64-portbld-freebsd12.2
Linked libs: libevent 2.1.12-stable (it uses kqueue), OpenSSL 1.1.1h-freebsd  24 Aug 2021
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
I want to sleep

This is a bug in `unbound-checkconf`

`/usr/local/sbin/unbound -c /usr/local/etc/unbound/unbound.conf`  runs like a sharm.

**Comment by gthess** [comment] 2022-01-26 10:34
Hi, this seems like a duplicate of #574 and it should already be fixed in 1.14.0.

**Closed as completed by gthess** 2022-01-26 10:34 UTC

**Comment by ip75** [comment] 2022-01-26 11:04
sorry. I didn't find #574 before made an issue

**Comment by gthess** [comment] 2022-01-26 11:07
No problem!
