### ISSUE TITLE
Unbound in version 1.10.1 is not respecting the external maximum ttl.

### ISSUE THREAD

**Issue by cardosocristian** [NLnetLabs/unbound#353] opened 2020-11-24 17:53 UTC
When using unbound in version 1.10 on my Centos 7 server, the external TTL is not respected, causing some problems in the generation of the server cache.
There are some zones that have a TTL greater than 86400 and this is not respected in Unbound, generating a higher consumption of external requests and some blocks in RBL providers.
Until then I did not explicitly set the cache-max-ttl parameter in the config and with that the external TTL was not being respected.
After I insert the following config in the unbound, the external ttl is respected again
cache-max-ttl: 864000

**Comment by gthess** [comment] 2021-06-16 16:05
Hi,

This is not a bug. Unbound specifically set limits on the allowed min and max TTL values as per https://datatracker.ietf.org/doc/html/rfc1035#section-7.3.

Based on what you are trying to achieve you can either use a higher `cache-max-ttl` as you have done.

Starting from version 1.13.1 you can also use `serve-original-ttl: yes`. This implicitly disables the min and max limits but it always returns the original TTL (without decrementing). As documented in the man page this is quite a unique option and not fit for normal DNS resolving; mainly for research.

**Closed as completed by gthess** 2021-06-16 16:05 UTC
