### ISSUE TITLE
Error while starting Unbound 1.13.2 on Ubuntu 20.04

### ISSUE THREAD

**Issue by utunnel** [NLnetLabs/unbound#534] opened 2021-08-24 05:42 UTC
**Describe the bug**
Following error occurred while trying to start complied version of unbound with pythonmodule.
Unbound version 1.13.2
OS: Ubuntu 20.4
Python: 3.8

root@*####*:/usr/local# /usr/local/unbound/sbin/unbound -vvv -c /usr/local/unbound/etc/unbound/unbound.conf -d
[1629781639] unbound[223253:0] notice: Start of unbound 1.13.2.
[1629781639] unbound[223253:0] debug: creating udp4 socket **.**.**.** **
[1629781639] unbound[223253:0] debug: creating tcp4 socket **.**.**.** **
[1629781639] unbound[223253:0] debug: switching log to syslog
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/unboundmodule.py", line 803, in <module>
    class module_env(_object):
  File "/usr/lib/python3/dist-packages/unboundmodule.py", line 873, in module_env
    __swig_setmethods__["now"] = _unboundmodule.module_env_now_set
AttributeError: module '_unboundmodule' has no attribute 'module_env_now_set'

**To reproduce**
1. tar zxvf unbound-1.13.2.tar.gz
2. cd unbound-1.13.2
3. ln -s /usr/bin/python3 /usr/bin/python
4. ./configure --prefix=/usr/local/unbound --with-pyunbound --with-libevent --with-pythonmodule
5. make
6. make install
7. ./unbound -d

**Expected behavior**
unbound gets started without any error.

**System:**
 - Unbound version: 1.13.2
 - OS: Ubuntu 20.04
 - `unbound -V` output:   
 
 root@*****:/usr/local# /usr/local/unbound/sbin/unbound -V                                                    
Version 1.13.2

Configure line: --prefix=/usr/local/unbound --with-pyunbound --with-libevent --with-pythonmodule
Linked libs: libevent 2.1.11-stable (it uses epoll), OpenSSL 1.1.1f  31 Mar 2020
Linked modules: dns64 python respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Comment by gthess** [comment] 2023-03-17 13:58
Closing this as a duplicate of #769. More discussion and suggestions in that issue.

**Closed as completed by gthess** 2023-03-17 13:58 UTC
