### ISSUE TITLE
unbound-control-setup hangs sometimes depending on the openssl version

### ISSUE THREAD

**Issue by Jakker** [NLnetLabs/unbound#1149] opened 2024-10-03 10:48 UTC
**Describe the bug**
unbound-contro;-setup hangs sometimes depending on the openssl version

**To reproduce**
Run the script when an old version is installed

**Expected behavior**

**System:**
 - Unbound version: unbound-1.21.0
 - OS: FreeBSD and probably others
 - `unbound -V` output: Not relevant

**Additional information**
See FreeBSD bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281804
and proposed solution: https://bugs.freebsd.org/bugzilla/attachment.cgi?id=253969&action=diff

**Comment by wcawijngaards** [comment] 2024-10-08 07:21
I think this is a duplicate of #1126 . I do not mind adding the 'openssl version' as the additional parameter on the commandline, but perhaps the commit that fixes that issue already fixed this one as well.

**Closed as completed** 2024-10-08 09:54 UTC

**Comment by wcawijngaards** [comment] 2024-10-08 09:55
Committed the fix. This is in addition to the other fix, which looks to be fine. Thanks for the patch provided!
