### ISSUE TITLE
I dont know why the forward function doesn't work.

### ISSUE THREAD

**Issue by silveric10** [NLnetLabs/unbound#45] opened 2019-06-25 12:22 UTC
I only made these changes below to the unbound.conf. I want to forward all my dns queries to port 9999, but it doesn't work. 
 interface:127.0.0.1@8888
 forward-zone
         name: "."
         forward-addr: 127.0.0.1@9999
Can you help to explain?

**Comment by wcawijngaards** [comment] 2019-06-25 12:27
You need the option `do-not-query-localhost: no` in unbound.conf.
The previous default value was yes and this prevented messages to 127.0.0.1 from the forward-addr.

**Comment by wcawijngaards** [comment] 2019-06-25 12:28
(Closing this because I think it resolved your issue, if it did not resolve the issue, please explain more about what is going wrong).

**Closed as completed by wcawijngaards** 2019-06-25 12:27 UTC

**Comment by bjovereinder** [comment] 2019-06-25 12:33
This seems a legitimate question for the Unbound mailing list, not a bug report.

— Benno

**Comment by wcawijngaards** [comment] 2019-06-25 12:52
The commit above makes unbound-checkconf print out warnings for the matter, since other people also experience this as a surprise, I thought that could be helpful.  Looks like this:
```unbound-checkconf: warning: forward-addr: '127.0.0.1' is specified for forward-zone: '.', but do-not-query-localhost: yes means that the address will not be used for lookups.```
